// Code generated by agentflow v0.5.1; DO NOT EDIT.

package prompts

import (
	"strings"
)

type SystemPrompt struct{}

func (input *SystemPrompt) String() string {
	return "You are a helpful coding assistant. You answer programming questions clearly and concisely.\nWhen providing code examples, always include comments explaining the key parts."
}

type AnswerQuestion struct {
	Topic    string
	Question string
	Context  string
}

func (input *AnswerQuestion) String() string {
	var b strings.Builder
	length := 0
	length += 48
	length += len(input.Topic)
	length += 3
	length += len(input.Question)
	length += 42
	if input.Context != "" {
		length += 34
		length += len(input.Context)
		length += 1
	}
	b.Grow(length)
	b.WriteString("The user has asked the following question about ")
	b.WriteString(input.Topic)
	b.WriteString(":\n\n")
	b.WriteString(input.Question)
	b.WriteString("\n\nPlease provide a clear, concise answer.\n")
	if input.Context != "" {
		b.WriteString("\nHere is some additional context:\n")
		b.WriteString(input.Context)
		b.WriteRune('\n')
	}
	return b.String()
}

type SummarizeConversation struct {
	Messages string
}

func (input *SummarizeConversation) String() string {
	var b strings.Builder
	length := 0
	length += 126
	length += len(input.Messages)
	length += 10
	b.Grow(length)
	b.WriteString("Summarize the following conversation between a user and an assistant.\nFocus on the key questions asked and answers provided.\n\n")
	b.WriteString(input.Messages)
	b.WriteString("\n\nSummary:")
	return b.String()
}
