// Code generated by agentflow v0.5.1; DO NOT EDIT.

package prompts

import (
	"strconv"
	"strings"
)

type CodeReviewSystem struct{}

func (input *CodeReviewSystem) String() string {
	return "You are a senior code reviewer. Review the submitted code for correctness, readability, and performance.\nRate issues on a scale of 1-5 severity."
}

type ReviewCode struct {
	Author string
	Code   struct {
		Language    string
		Filename    string
		Content     string
		Description string
	}
	Pr struct {
		IsDraft      bool
		LinesChanged int
	}
}

func (input *ReviewCode) isCodeZero() bool {
	return input.Code.Language == "" &&
		input.Code.Filename == "" &&
		input.Code.Content == "" &&
		input.Code.Description == ""
}

func (input *ReviewCode) isPrZero() bool {
	return !input.Pr.IsDraft &&
		input.Pr.LinesChanged == 0
}

func (input *ReviewCode) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.Pr.LinesChanged)
	length := 0
	length += 36
	length += len(input.Author)
	length += 15
	length += len(input.Code.Language)
	length += 11
	length += len(input.Code.Filename)
	length += 5
	length += len(input.Code.Language)
	length += 1
	length += len(input.Code.Content)
	length += 6
	if input.Code.Description != "" {
		length += 18
		length += len(input.Code.Description)
		length += 1
	}
	length += 2
	if input.Pr.IsDraft {
		length += 94
	}
	length += 2
	if input.Pr.LinesChanged != 0 {
		length += 1
		if input.Pr.LinesChanged >= 500 {
			length += 34
			length += len(var0)
			length += 67
		}
		length += 1
	}
	length += 170
	b.Grow(length)
	b.WriteString("## Code Review Request\n\n**Author**: ")
	b.WriteString(input.Author)
	b.WriteString("\n**Language**: ")
	b.WriteString(input.Code.Language)
	b.WriteString("\n**File**: ")
	b.WriteString(input.Code.Filename)
	b.WriteString("\n\n```")
	b.WriteString(input.Code.Language)
	b.WriteRune('\n')
	b.WriteString(input.Code.Content)
	b.WriteString("\n```\n\n")
	if input.Code.Description != "" {
		b.WriteString("\n**Description**: ")
		b.WriteString(input.Code.Description)
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.Pr.IsDraft {
		b.WriteString("\nNote: This is a draft PR — focus on high-level architecture feedback rather than nitpicks.\n")
	}
	b.WriteString("\n\n")
	if input.Pr.LinesChanged != 0 {
		b.WriteRune('\n')
		if input.Pr.LinesChanged >= 500 {
			b.WriteString("\nWarning: This is a large change (")
			b.WriteString(var0)
			b.WriteString(" lines). Consider suggesting the author break it into smaller PRs.\n")
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\nPlease review this code and provide feedback on:\n1. Correctness and potential bugs\n2. Code style and readability\n3. Performance considerations\n4. Suggested improvements")
	return b.String()
}
