// Code generated by agentflow v0.5.1; DO NOT EDIT.

package prompts

import (
	"strings"
)

type GenerateCommitMessage struct {
	Diff     string
	TicketId string
}

func (input *GenerateCommitMessage) String() string {
	var b strings.Builder
	length := 0
	length += 145
	length += len(input.Diff)
	length += 6
	if input.TicketId != "" {
		length += 19
		length += len(input.TicketId)
		length += 1
	}
	length += 17
	b.Grow(length)
	b.WriteString("Write a concise git commit message for the following diff.\nFollow conventional commits format (feat, fix, refactor, docs, test, chore).\n\n```diff\n")
	b.WriteString(input.Diff)
	b.WriteString("\n```\n\n")
	if input.TicketId != "" {
		b.WriteString("\nReference ticket: ")
		b.WriteString(input.TicketId)
		b.WriteRune('\n')
	}
	b.WriteString("\n\ncommit message:")
	return b.String()
}
