// Code generated by agentflow v0.5.1; DO NOT EDIT.

package prompts

import (
	"strconv"
	"strings"
)

type ErrorExplanationSystem struct{}

func (input *ErrorExplanationSystem) String() string {
	return "You are a debugging assistant. You explain error messages in plain language and suggest fixes.\nAlways provide the most likely cause first."
}

type ExplainError struct {
	Language     string
	ErrorMessage string
	StackTrace   string
	File         struct {
		Name string
		Line int
	}
}

func (input *ExplainError) isFileZero() bool {
	return input.File.Name == "" &&
		input.File.Line == 0
}

func (input *ExplainError) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.File.Line)
	length := 0
	length += 34
	length += len(input.Language)
	length += 15
	length += len(input.ErrorMessage)
	length += 6
	if input.StackTrace != "" {
		length += 18
		length += len(input.StackTrace)
		length += 5
	}
	length += 2
	if input.File.Name != "" {
		length += 7
		length += len(input.File.Name)
		length += 1
		if input.File.Line != 0 {
			length += 7
			length += len(var0)
			length += 1
		}
		length += 1
	}
	length += 84
	b.Grow(length)
	b.WriteString("The following error occurred in a ")
	b.WriteString(input.Language)
	b.WriteString(" project:\n\n```\n")
	b.WriteString(input.ErrorMessage)
	b.WriteString("\n```\n\n")
	if input.StackTrace != "" {
		b.WriteString("\nStack trace:\n```\n")
		b.WriteString(input.StackTrace)
		b.WriteString("\n```\n")
	}
	b.WriteString("\n\n")
	if input.File.Name != "" {
		b.WriteString("\nFile: ")
		b.WriteString(input.File.Name)
		b.WriteRune('\n')
		if input.File.Line != 0 {
			b.WriteString("\nLine: ")
			b.WriteString(var0)
			b.WriteRune('\n')
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\nPlease explain:\n1. What this error means\n2. The most likely cause\n3. How to fix it")
	return b.String()
}
