// Code generated by agentflow v0.5.1; DO NOT EDIT.

package prompts

import (
	"strconv"
	"strings"
)

type TestGenerationSystem struct{}

func (input *TestGenerationSystem) String() string {
	return "You are a test engineer. Generate comprehensive test cases for the given code.\nInclude edge cases, error cases, and happy paths."
}

type GenerateTests struct {
	TestFramework  string
	Language       string
	SourceCode     string
	FunctionName   string
	CoverageTarget int
	ExistingTests  string
}

func (input *GenerateTests) String() string {
	var b strings.Builder
	var0 := strconv.Itoa(input.CoverageTarget)
	length := 0
	length += 9
	length += len(input.TestFramework)
	length += 25
	length += len(input.Language)
	length += 11
	length += len(input.Language)
	length += 1
	length += len(input.SourceCode)
	length += 6
	if input.FunctionName != "" {
		length += 23
		length += len(input.FunctionName)
		length += 12
	}
	length += 2
	if input.CoverageTarget != 0 {
		length += 1
		if input.CoverageTarget >= 90 {
			length += 23
			length += len(var0)
			length += 48
		}
		length += 1
		if input.CoverageTarget <= 50 {
			length += 38
			length += len(var0)
			length += 10
		}
		length += 1
	}
	length += 2
	if input.ExistingTests != "" {
		length += 46
		length += len(input.ExistingTests)
		length += 5
	}
	b.Grow(length)
	b.WriteString("Generate ")
	b.WriteString(input.TestFramework)
	b.WriteString(" tests for the following ")
	b.WriteString(input.Language)
	b.WriteString(" code:\n\n```")
	b.WriteString(input.Language)
	b.WriteRune('\n')
	b.WriteString(input.SourceCode)
	b.WriteString("\n```\n\n")
	if input.FunctionName != "" {
		b.WriteString("\nFocus on testing the `")
		b.WriteString(input.FunctionName)
		b.WriteString("` function.\n")
	}
	b.WriteString("\n\n")
	if input.CoverageTarget != 0 {
		b.WriteRune('\n')
		if input.CoverageTarget >= 90 {
			b.WriteString("\nTarget high coverage (")
			b.WriteString(var0)
			b.WriteString("%). Include edge cases and boundary conditions.\n")
		}
		b.WriteRune('\n')
		if input.CoverageTarget <= 50 {
			b.WriteString("\nFocus on the critical paths only — ")
			b.WriteString(var0)
			b.WriteString("% target.\n")
		}
		b.WriteRune('\n')
	}
	b.WriteString("\n\n")
	if input.ExistingTests != "" {
		b.WriteString("\nHere are the existing tests for context:\n```\n")
		b.WriteString(input.ExistingTests)
		b.WriteString("\n```\n")
	}
	return b.String()
}
